################################################################################
# Simulate                                                                     #
#                                                                              #
"""Module to convert GROMACS .gro files to LAMMPS data files."""               #
################################################################################

import numpy as np
import os
import sys


def line_mapper(line):
    """
    Map a line from a .gro file to its components.
    
    Parameters
    ----------
    line : str
        A line from a .gro file.

    Returns
    -------
    tuple
        A tuple containing:
        - res_id (int): Residue ID
        - res_name (str): Residue name
        - atom_name (str): Atom name
        - x (float): X coordinate in Angstroms
        - y (float): Y coordinate in Angstroms
        - z (float): Z coordinate in Angstroms
        - vx (float): X velocity in Angstroms/ps
        - vy (float): Y velocity in Angstroms/ps
        - vz (float): Z velocity in Angstroms/ps
    """
    res_id = int(line[0:5].strip())
    res_name = line[5:10].strip()
    atom_name = line[10:15].strip().translate(str.maketrans("", "", "0123456789"))
    x = float(line[20:28].strip()) * 10
    y = float(line[28:36].strip()) * 10
    z = float(line[36:44].strip()) * 10
    vx = float(line[44:52].strip()) / 100
    vy = float(line[52:60].strip()) / 100
    vz = float(line[60:68].strip()) / 100
    return res_id, res_name, atom_name, x, y, z, vx, vy, vz

def read_gro_file(file_path):
    """
    Read a GROMACS .gro file and extract box dimensions and atom data.

    Parameters
    ----------
    file_path : str
        Path to the .gro file.

    Returns
    -------
    tuple
        A tuple containing:
        - box_dims (list): List of box dimensions [x, y, z] in Angstroms
        - gro_data (list): List of tuples with atom data
    """
    with open(file_path, 'r') as file:
        lines = file.readlines()
        
    box_dims = [float(dim) * 10 for dim in lines[-1].strip().split()]
    print(box_dims)
    # box = [x for x in lines[-1].split(" ") if x != ""]
    
    gro_data = [line_mapper(line) for line in lines[2:-1]]

    return box_dims, gro_data

def write_lammps_header(file, num_atoms, num_atom_types, box_dims, atom_masses):
    """
    Write the header section of a LAMMPS data file.
    
    Parameters
    ----------
    file : file object
        The file object to write to.
    num_atoms : int
        Number of atoms.
    num_atom_types : int
        Number of atom types.
    box_dims : list
        List of box dimensions [x, y, z] in Angstroms.
    atom_masses : dict
        Dictionary mapping atom type to mass."""
    file.write("System generated by PoreReax package\n\n")
    file.write(f"{num_atoms} atoms\n")
    file.write(f"{num_atom_types} atom types\n\n")
    file.write(f"{0.0:8.3f} {box_dims[0]:8.3f} xlo xhi\n")
    file.write(f"{0.0:8.3f} {box_dims[1]:8.3f} ylo yhi\n")
    file.write(f"{0.0:8.3f} {box_dims[2]:8.3f} zlo zhi\n\n")
    file.write("Masses\n\n")
    for atom_type, mass in atom_masses.items():
        file.write(f"{atom_type} {mass:8.3f}\n")

def write_lammps_data(file, gro_data, atom_lib, atom_charges):
    """
    Write the atom and velocity sections of a LAMMPS data file.

    Parameters
    ----------
    file : file object
        The file object to write to.
    gro_data : list
        List of tuples with atom data.
    atom_lib : dict
        Dictionary mapping atom names to atom types.
    atom_charges : dict
        Dictionary mapping atom names to charges.
    """
    file.write("\nAtoms\n\n")
    for i, data in enumerate(gro_data):
        res_id, _, atom_name, x, y, z, _, _, _ = data
        atom_type = atom_lib.get(atom_name)
        charge = atom_charges.get(atom_name)
        if atom_type is None:
            raise ValueError(f"Atom name '{atom_name}' not found in atom library.")
        if charge is None:
            raise ValueError(f"Charge for atom name '{atom_name}' with type '{atom_type}' not found in atom charges.")
        file.write(f"{i+1:5d} {res_id:5d} {atom_type:5d} {charge:8.3f} {x:8.3f} {y:8.3f} {z:8.3f}\n")
    file.write("\nVelocities\n\n")
    for i, data in enumerate(gro_data):
        _, _, _, _, _, _, vx, vy, vz = data
        file.write(f"{i+1:5d} {vx: 2.6f} {vy: 2.6f} {vz: 2.6f}\n")

def construct(source_path, file_path, atom_lib, atom_masses, atom_charges):
    """
    Convert a GROMACS .gro file to a LAMMPS data file.

    Parameters
    ----------
    source_path : str
        Path to the source .gro file.
    file_path : str
        Path to the output LAMMPS data file.
    atom_lib : dict
        Dictionary mapping atom names to atom types.
    atom_masses : dict
        Dictionary mapping atom types to masses.
    atom_charges : dict
        Dictionary mapping atom names to charges.
    """
    box_dims, gro_data = read_gro_file(source_path)
    gro_data = [data for data in gro_data if atom_lib.get(data[2], 0) != -1] # Filter out ghost particles e.g. from tip4p water model     
    num_atoms = len(gro_data)
    num_atom_types = max(atom_lib.values())
    with open(file_path, 'w') as file:
        write_lammps_header(file, num_atoms, num_atom_types, box_dims, atom_masses)
        write_lammps_data(file, gro_data, atom_lib, atom_charges)
    print(f"LAMMPS data file written to {file_path}")