#!/bin/bash
#SBATCH --nodes={{ SIMULATIONNODES }}
#SBATCH --ntasks-per-node={{ SIMULATIONTASKSPERNODE }}
#SBATCH --time={{ SIMULATIONTIME }}
#SBATCH --job-name={{ SIMULATIONLABEL }}
#SBATCH --error=%x_%j.err
#SBATCH --output=%x_%j.out
#SBATCH --partition=cpu

module purge
. /opt/bwhpc/common/etc/easybuild/enable_eb_modules
module load LAMMPS/2Aug2023_update2-foss-2023a-kokkos

{{ LAMMPS_COMMAND }}